name: Fixups

on:
  workflow_dispatch:

jobs:
  fixes:
    runs-on: ubuntu-latest

    timeout-minutes: 10

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Repair screenshots
        run: ./gradlew verifyAndRecordRoborazziDebug

      - name: Push new screenshots if available
        uses: stefanzweifel/git-auto-commit-action@v5
        if: ${{ always() }}
        with:
          file_pattern: '**/*.png'
          disable_globbing: true
          commit_message: "🤖 Updates screenshots"
